apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-api.fullname" . }}
  labels:
    {{- include "go-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.healthport }}
      targetPort: {{ .Values.service.healthport }}
      protocol: TCP
      name: internal
  selector:
    {{- include "go-api.selectorLabels" . | nindent 4 }}